version: '3.3'
services:
  #PHP Service
  room_reservation_php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php81
    container_name: room_reservation_php
    tty: true
    environment:
      SERVICE_NAME: room_reservation_php
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ../:/var/www:delegated
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini:delegated
    networks:
      - docker_network_bridge

  #Composer Service, it is to create vendor folder for project
  room_reservation_composer:
    image: composer/composer:latest
    command: install
    volumes:
      - ../:/app

  #Nginx Service
  room_reservation_webserver:
    image: nginx:alpine
    container_name: room_reservation_webserver
    tty: true
    ports:
      - "8087:80"
      - "8088:443"
    volumes:
      - ../:/var/www:delegated
      - ./nginx/conf.d/:/etc/nginx/conf.d/:delegated
      - ./nginx/certs:/etc/nginx/certs:delegated
    networks:
      - docker_network_bridge

  #Redis Service
  room_reservation_redis:
    image: redis:alpine
    container_name: room_reservation_redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6380:6379'
    volumes:
      - ./redis:/data
    networks:
      - docker_network_bridge

  #MySQL Service
  room_reservation_database:
    image: mysql:5.7
    container_name: room_reservation_database
    tty: true
    ports:
      - "33078:3306"
    environment:
      MYSQL_DATABASE: missafir_api_db
      MYSQL_ROOT_PASSWORD: test
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql_data:/var/lib/mysql/:delegated
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - docker_network_bridge

  #Elasticsearch Service
  room_reservation_elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: room_reservation_elasticsearch
    environment:
      - node.name=room_reservation_elasticsearch
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=room_reservation_elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - ./es01:/usr/share/elasticsearch/data
    networks:
      - docker_network_bridge

  #Kibana Service
  room_reservation_kibana:
    image: docker.elastic.co/kibana/kibana:7.13.4
    container_name: room_reservation_kibana
    environment:
      ELASTICSEARCH_URL: http://room_reservation_elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://room_reservation_elasticsearch:9200"]'
    ports:
      - "5601:5601"
    networks:
      - docker_network_bridge

#Docker Networks
networks:
  docker_network_bridge:
    driver: bridge

#Volumes
volumes:
  mysql_data:
    driver: local
